--CREATE INDEXES

CREATE INDEX IDX_ATENDIMENTO_SEQCLIENTE ON TB_ATENDIMENTO(SEQCLIENTE);
CREATE INDEX IDX_ATENDIMENTO_SEQATENDENTE ON TB_ATENDIMENTO(SEQATENDENTE);
CREATE INDEX IDX_ATENDIMENTO_SEQMOTIVO ON TB_ATENDIMENTO(SEQMOTIVO);
CREATE INDEX IDX_ATENDIMENTO_SEQPRODUTO ON TB_ATENDIMENTO(SEQPRODUTO);
CREATE INDEX IDX_ATENDIMENTO_SEQCANAL ON TB_ATENDIMENTO(SEQCANAL);
CREATE INDEX IDX_CANAL_SEQ ON TB_CANALATENDIMENTO (SEQCANAL);
CREATE INDEX IDX_PRODUTO_SEQ ON TB_PRODUTO(SEQPRODUTO, DEPARTAMENTO_RESPONSAVEL);
CREATE INDEX IDX_MOTIVO_SEQ ON TB_MOTIVO_ATENDIMENTO(SEQMOTIVO, NOME_MOTIVO);
CREATE INDEX IDX_MOTIVO_DPTO ON TB_MOTIVO_ATENDIMENTO(DEPARTAMENTO_RESPONSAVEL);
CREATE INDEX IDX_ATENDENTE_SEQ ON TB_ATENDENTE(SEQATENDENTE);
CREATE INDEX IDX_ATENDENTE_DPTO ON TB_ATENDENTE(SEQDEPARTAMENTO); 
CREATE INDEX IDX_DPTO ON TB_DEPARTAMENTO(SEQDEPARTAMENTO, NOME_DEPARTAMENTO);
CREATE INDEX IDX_CLIENTE_CPF ON TB_CLIENTE(CPF);
CREATE INDEX IDX_CLIENTE_SEQ ON TB_CLIENTE(SEQCLIENTE); 