CREATE DATABASE CALLCENTER;

CREATE TABLE TB_CLIENTE (
	SEQCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(250) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL);
    
CREATE TABLE TB_DEPARTAMENTO (
		SEQDEPARTAMENTO INT AUTO_INCREMENT PRIMARY KEY,
        NOME_DEPARTAMENTO VARCHAR(150) NOT NULL,
        DATA_CRIACAO DATETIME NOT NULL);
        
CREATE TABLE TB_ATENDENTE (
	SEQATENDENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ATENDENTE VARCHAR(150) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    SEQDEPARTAMENTO INT NOT NULL,
    NIVEL_EXPERIENCIA VARCHAR(100) NOT NULL,
    TURNO_TRABALHO VARCHAR(40) NOT NULL,
    DATA_ADMISSAO DATETIME NOT NULL,
    DATA_ALTERACAO DATETIME,
    FOREIGN KEY (SEQDEPARTAMENTO) REFERENCES TB_DEPARTAMENTO(SEQDEPARTAMENTO)
    );
    
    CREATE TABLE TB_MOTIVO_ATENDIMENTO(
    SEQMOTIVO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MOTIVO VARCHAR(150) NOT NULL,
    PRIORIDADE INT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_ALTERACAO DATETIME,
    DEPARTAMENTO_RESPONSAVEL INT NOT NULL,
    FOREIGN KEY (DEPARTAMENTO_RESPONSAVEL) REFERENCES TB_DEPARTAMENTO(SEQDEPARTAMENTO)
    );
    
    CREATE TABLE TB_PRODUTO
    (SEQPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
	NOME_PRODUTO VARCHAR(150) NOT NULL,
    DESCRICAO_PRODUTO_DETALHADA VARCHAR(300) NOT NULL,
    PRECO DECIMAL NOT NULL,
    DEPARTAMENTO_RESPONSAVEL INT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    DATA_ALTERACAO DATETIME,
    STATUS_PRODUTO CHAR(1),
    FOREIGN KEY (DEPARTAMENTO_RESPONSAVEL) REFERENCES TB_DEPARTAMENTO(SEQDEPARTAMENTO));
    
    CREATE TABLE TB_CANALATENDIMENTO
    (SEQCANAL INT AUTO_INCREMENT PRIMARY KEY,
		NOME_CANAL VARCHAR(150) NOT NULL,
        INFORMACOES_CANAL VARCHAR(300) NOT NULL,
        TEMPO_RESPOSTA DECIMAL,
        DISPONIBILIDADE VARCHAR(50),
        STATUS_CANAL CHAR(1));
        
   CREATE TABLE TB_ATENDIMENTO(
   SEQATENDIMENTO INT AUTO_INCREMENT PRIMARY KEY,
   DATA_HORA_INICIO_ATENDIMENTO DATETIME NOT NULL,
   DATA_HORA_FIM_ATENDIMENTO DATETIME,
   SEQCLIENTE INT NOT NULL,
   SEQATENDENTE INT NOT NULL,
   SEQMOTIVO INT NOT NULL,
   PROTOCOLO VARCHAR(50) NOT NULL,
   SEQPRODUTO INT NOT NULL,
   SEQCANAL INT NOT NULL,
   ENPS TINYINT UNSIGNED,
   FOREIGN KEY (SEQCLIENTE) REFERENCES TB_CLIENTE(SEQCLIENTE),
   FOREIGN KEY (SEQATENDENTE) REFERENCES TB_ATENDENTE(SEQATENDENTE),
   FOREIGN KEY (SEQMOTIVO) REFERENCES TB_MOTIVO_ATENDIMENTO(SEQMOTIVO),
   FOREIGN KEY (SEQPRODUTO) REFERENCES TB_PRODUTO(SEQPRODUTO),
   FOREIGN KEY (SEQCANAL) REFERENCES TB_CANALATENDIMENTO(SEQCANAL));