# Média de tempo por motivo de atendimento ;

SELECT 
    M.SEQMOTIVO,
    M.NOME_MOTIVO,
    SEC_TO_TIME(ROUND(AVG(TIME_TO_SEC(TEMPO_MEDIO_RESOLUCAO_HORAS)))) AS MEDIA_TEMPO_MEDIO_RESOLUCAO_HORAS
FROM (
    SELECT 
        A.SEQMOTIVO,
        SEC_TO_TIME(ROUND(AVG(TIMESTAMPDIFF(SECOND, A.DATA_HORA_INICIO_ATENDIMENTO, A.DATA_HORA_FIM_ATENDIMENTO)) / 3600)) AS TEMPO_MEDIO_RESOLUCAO_HORAS
    FROM 
        TB_ATENDIMENTO A
    WHERE 
        A.DATA_HORA_FIM_ATENDIMENTO IS NOT NULL
        AND YEAR(A.DATA_HORA_INICIO_ATENDIMENTO) = 2024
    GROUP BY 
        A.SEQMOTIVO
) AS subquery
INNER JOIN TB_MOTIVO_ATENDIMENTO M ON subquery.SEQMOTIVO = M.SEQMOTIVO
GROUP BY 
    M.SEQMOTIVO, M.NOME_MOTIVO;