# RELATÓRIO DE CHAMADOS POR SEGMENTAÇÃO DE DEPARTAMENTO, SENDO MÊS, ANO, TOTAL ATENDIMENTOS REFERENTE A CADA MÊS, QUANTOS ANTENDIMENTOS FORAM RESOLVIDOS E A TAXA DE RESOLUÇÃO.

SELECT 
    D.NOME_DEPARTAMENTO,
    MONTH(A.DATA_HORA_INICIO_ATENDIMENTO) AS MES,
    YEAR(A.DATA_HORA_INICIO_ATENDIMENTO) AS ANO,
    COUNT(A.SEQATENDIMENTO) AS TOTAL_ATENDIMENTOS,
    COUNT(CASE WHEN A.DATA_HORA_FIM_ATENDIMENTO IS NOT NULL THEN 1 END) AS ATENDIMENTOS_RESOLVIDOS,
    ROUND((COUNT(CASE WHEN A.DATA_HORA_FIM_ATENDIMENTO IS NOT NULL THEN 1 END) / COUNT(A.SEQATENDIMENTO)) * 100, 2) AS TAXA_RESOLUCAO
FROM 
    TB_ATENDIMENTO A
    INNER JOIN TB_ATENDENTE AT ON A.SEQATENDENTE = AT.SEQATENDENTE
    INNER JOIN TB_DEPARTAMENTO D ON AT.SEQDEPARTAMENTO = D.SEQDEPARTAMENTO
GROUP BY 
    D.NOME_DEPARTAMENTO,
    MONTH(A.DATA_HORA_INICIO_ATENDIMENTO),
    YEAR(A.DATA_HORA_INICIO_ATENDIMENTO);