
# KPI DE NOME ATENDENTE, MÊS, ANO E NÚMERO DE ATENDIMENTOS POR MÊS.

SET lc_time_names='pt_PT';

CREATE VIEW VW_RELATORIO_DIARIO AS
SELECT 
    AT.NOME_ATENDENTE,
    MONTHNAME(A.DATA_HORA_INICIO_ATENDIMENTO) AS MES,
    YEAR(A.DATA_HORA_INICIO_ATENDIMENTO) AS ANO,
    COUNT(A.SEQATENDIMENTO) AS NUMERO_ATENDIMENTOS
FROM 
    TB_ATENDIMENTO A
    INNER JOIN TB_ATENDENTE AT ON A.SEQATENDENTE = AT.SEQATENDENTE
GROUP BY 
    AT.NOME_ATENDENTE,
    MONTHNAME(A.DATA_HORA_INICIO_ATENDIMENTO),
    YEAR(A.DATA_HORA_INICIO_ATENDIMENTO);