#Relatório Tempo Médio de Resolução de Atendimentos por Canal de Atendimento e motivos relacionados.

SELECT 
    C.NOME_CANAL,
    M.NOME_MOTIVO,
    SEC_TO_TIME(ROUND(AVG(TIMESTAMPDIFF(SECOND, A.DATA_HORA_INICIO_ATENDIMENTO, A.DATA_HORA_FIM_ATENDIMENTO)) / 3600)) AS TEMPO_MEDIO_RESOLUCAO_HORAS
FROM 
    TB_ATENDIMENTO A
    INNER JOIN TB_CANALATENDIMENTO C ON A.SEQCANAL = C.SEQCANAL
    INNER JOIN TB_MOTIVO_ATENDIMENTO M ON A.SEQMOTIVO = M.SEQMOTIVO
WHERE 
    A.DATA_HORA_FIM_ATENDIMENTO IS NOT NULL
GROUP BY 
    C.NOME_CANAL,
    M.NOME_MOTIVO
ORDER BY 
    TEMPO_MEDIO_RESOLUCAO_HORAS DESC;
